### ISSUE TITLE
Shiny server not referencing project-specific lib path using packrat (except on Pro edition)

### ISSUE THREAD

**Issue by jburos** [rstudio/shiny-server#143] opened 2015-08-21 22:33 UTC
Hi,

I'm not sure how to give a reproducible example of this, so I apologize in advance ... I will try to give as much background as I can.

I have a tst environment using shiny server community edition & whereas my dev & prod environments use shiny server pro.  The problem is that shiny-server COMMUNITY edition fails to load the packrat library, whereas shiny-server PRO edition succeeds in referencing the packrat library. 

I am logging this here because it would be very useful for shiny-server to make use of project-specific packrat libraries where they exist. I'm not sure exactly why this isn't working, except that the I have the PRO edition `utilization_scheduler` set to launch a new session for each connection, which may mean that each project gets initialized separately? 

The community edition is: Shiny Server v1.4.0.721 (Node.js v0.10.21)
The pro edition is: Shiny Server (Commercial) v1.4.0.637 (Node.js v0.10.21)
Both are running on VMs with RHEL7 & they are otherwise similar builds. 

__ Background __ 
We have several apps in deployment using gitlab-ci (EE) for deployment.  Each app uses packrat to isolate package-specific effects from the other projects. There is nothing other than packrat & shiny in the site-wide LIB for both boxes.

In this case, I have an identical app deployed to both boxes using the same gitlab-ci deploy script from the same commit hash.  

Our deploy logs looks similar for the two builds, e.g.: 

```
Removing caTools ... OK
Removing gdata ... OK
Replacing R6 (upgrade 2.1.0 to 2.1.1) ... 	OK (built source)
Replacing dplyr (upgrade 0.4.2 to 0.4.2.9002) ... 	OK (built source)
Replacing shiny (upgrade 0.12.1.9001 to 0.12.2) ... 	OK (built source)
Replacing netezza (upgrade 0.6-3 to 0.6-3.1) ... 	OK (built source)
Up to date.
```

You may recognize the above as output from having run `packrat::restore()`

At any rate, when I browse to the app on the tst box which runs the community edition, I get a message `ERROR: there is no package called â€˜ggplot2â€™`. When I browse to the same app on our dev box which runs the pro edition, I see the app as expected.

**Comment by tareefk** [comment] 2015-08-24 15:45
Which version of shiny server are you running Jacki?

**Comment by jburos** [comment] 2015-08-24 16:21
The community edition is: Shiny Server v1.4.0.721 (Node.js v0.10.21)
The pro edition is: Shiny Server (Commercial) v1.4.0.637 (Node.js v0.10.21)

**Comment by fereshtehRS** [comment] 2015-08-24 17:30
Can you please provide some more info on this:
- How are you using/referencing the packrat library?
- When you say it fails on the open source version, where do you see the failure? Is it during the application launch? What is the error?
- Can you share the shiny-server.conf file from both systems with us?

**Comment by jburos** [comment] 2015-08-25 01:05
Hi Fereshteh,

The packrat library is a project-specific library; with standard setup after having run `packrat::init()`. We typically use the following statement : 

```
packrat::init(project = '.', options = list(local.repos = c("/analytics/users/jburos/local-cran")))
```

The resulting git repo then includes the */src directory but not the */lib directory.

In the deployment phase, we first clone the git repo into the correct path & then run the following : 

```
(cd $full_path && R --slave -f packrat/init.R --args --bootstrap-packrat && R --slave -e "packrat::restore()")
(cd $full_path && /bin/R --slave -e "packrat::status()")
```

This typically runs fine - resulting in an up to date message.

The final directory structure looks something like:

```
[gitlab-runner@#### #####]$ ls -la
total 176
drwxrwxr-x 6 gitlab-runner gitlab-runner  1024 Aug 24 11:57 .
drwxrwxr-x 4 gitlab-runner gitlab-runner  1024 Aug 21 19:48 ..
-rw-rw-r-- 1 gitlab-runner gitlab-runner 11373 Aug 21 17:35 app.R
-rw-rw-r-- 1 gitlab-runner gitlab-runner 58846 Aug 21 17:02 copy_csv_xls_pdf.swf
-rw-rw-r-- 1 gitlab-runner gitlab-runner  2232 Aug 21 17:02 copy_csv_xls.swf
-rw-rw-r-- 1 gitlab-runner gitlab-runner    56 Aug 21 17:35 .gitignore
-rw-rw-r-- 1 gitlab-runner gitlab-runner   685 Aug 21 19:48 .gitlab-ci.yml
drwxrwxr-x 2 gitlab-runner gitlab-runner  1024 Aug 21 17:35 helper_functions
drwxrwxr-x 2 gitlab-runner gitlab-runner  1024 Aug 21 17:02 models
drwxrwxr-x 6 gitlab-runner gitlab-runner  1024 Aug 24 11:57 packrat
-rw-rw-r-- 1 gitlab-runner gitlab-runner   205 Aug 21 17:02 RecommendedPrice.Rproj
-rw-rw-r-- 1 gitlab-runner gitlab-runner     0 Aug 24 11:57 restart.txt
-rw-rw-r-- 1 gitlab-runner gitlab-runner   117 Aug 21 17:02 .Rprofile
-rw-rw-r-- 1 gitlab-runner gitlab-runner   420 Aug 21 17:02 setup.R
drwxrwxr-x 2 gitlab-runner gitlab-runner  1024 Aug 21 17:02 www
```

In this case, the tst & prd servers serve the same content.

The error we see on the tst (community edition) server is a 500 internal error, with the message "ERROR: there is no package called â€˜ggplot2â€™"

Our shiny-server.conf is : 

*on prd* (using Pro edition):
```
# Instruct Shiny Server to run applications as the user "shiny"
run_as shiny;

# Specify the authentication method to be used.
# Initially, a flat-file database stored at the path below.
auth_passwd_file /etc/shiny-server/passwd;

# Define a server that listens on
server {
  listen ####;

  # Define a location at the base URL
  location / {

    # Only up tp 20 connections per Shiny process and at most 3 Shiny processes
    # per application. Proactively spawn a new process when our processes reach 
    # 90% capacity.
    utilization_scheduler 20 .9 3;

    # Host the directory of Shiny Apps stored in this directory
    site_dir #####;

    # Log all Shiny output to files in this directory
    log_dir #####;

    # When a user visits the base URL rather than a particular application,
    # an index of the applications available in this directory will be shown.
    directory_index on;
  }
}

# Provide the admin interface on port XXXX
admin XXXX {
  
  # Restrict the admin interface to the usernames listed here. Currently 
  # just one user named "####"
  required_user ####;
}
```

*on tst* (community edition):
```
# Instruct Shiny Server to run applications as the user "shiny"
run_as :HOME_USER: shiny;

# Define a server that listens on port ####
server {
  listen ####;

  # apps hosted out of user home directories (not sure if we will use these on tst)
  location /users {
    user_dirs on;
    directory_index on;
  }

 # Define a location at the base URL
  location / {
    run_as shiny;
    # Host the directory of Shiny Apps stored in this directory
    site_dir ####;

    # Log all Shiny output to files in this directory
    log_dir ####;

    #utilization_scheduler 1 0.5 10;

    # When a user visits the base URL rather than a particular application,
    # an index of the applications available in this directory will be shown.
    directory_index on;
  }
}
```

Welcome your feedback. Thanks & pls let me know if you have any other questions.

**Comment by fereshtehRS** [comment] 2015-08-25 15:17
Jacki, Thanks for providing all the info. Looking at your shiny-server.conf files from both servers, there are differences that could be contributing to the problem.

With Shiny Server Pro, you are using `site_dir` and `run_as shiny`. This will result in all R processes to be run as `shiny` user for any application you access.

With Shiny Server community edition, you have 2 different `location` settings; one is the same as above, but the other one uses `user_dirs`. Which one these is giving the issue? What URL do you access?

**Comment by jburos** [comment] 2015-08-25 16:10
Thanks Fereshteh.

The URL we are accessing is in prh_us/pricing_dashboard, so it should be
running as shiny user in both cases.

How would you recommend we modify the config file?

**Comment by fereshtehRS** [comment] 2015-08-25 19:37
Jacki, Your config files are fine. I just wanted to make sure you are using the same configuration in Pro and community setups.

I see the same behavior as you explained. This seems to be related to the way R processes are initiated, which is different between the Pro and community versions. This is partly intentional, but we will look into it.

**Comment by jburos** [comment] 2015-08-26 03:41
I suspected it might be related to that. Thanks for looking into it.

**Comment by trestletech** [comment] 2015-09-09 20:28
Hi there,

Sorry for the slow response, but I've just opened a pull request that, I believe, should fix this issue. The root of the problem is that RHEL7 changed the behavior of `su` which we use to switch users before spawning the R process. Once we get this change reviewed and merged, we'll cut a release that includes the fix.

And thanks for the wonderfully details bug report!

**Comment by jburos** [comment] 2015-09-09 20:47
That's great news! Thanks for your attention to this. Let me know if i can help test an early version

**Closed** 2015-09-09 22:13 UTC
