### ISSUE TITLE
CSS and JS files return 400 when request has Content-Length: 0

### ISSUE THREAD

**Issue by perrystephenson** [rstudio/shiny-server#401] opened 2019-07-17 23:28 UTC
In the beginning, Shiny Server was deployed on our internal container-as-a-service platform without any dramas. Life was good.

Then one of the platform teams put a reverse proxy in front of my container, and things broke. HTML was coming through just fine, but requests for the CSS and JS files were giving 400s. Not good.

The platform team did a whole bunch of investigation, and found a minimum reproducible example: if you add `Content-Length: 0` to the header of the request, you get a 400. If you remove `Content-Length: 0`, it works. The team is confident that adding `Content-Length: 0` is acceptable within the relevant standards, which makes it a bug with how Shiny Server handles the requests. They're happy to provide some tcp dumps if that's helpful.

There is a pretty easy workaround for me: I'm turning the proxy off. But we got into a discussion about R vs Python so I'm really hoping you can fix this bug so that I can point to this as an example of "look how good/strong the R open source community is!" But it's not critical for me, and probably shouldn't be high priority unless it's impacting others too.

And thanks for making such an awesome tool!

**Comment by cleemansen** [comment] 2020-05-19 06:41
I can confirm the described bug. Getting also a `400 - Bad Request` as soon as setting a request-header `Content-Length: 0`.

My reverse-proxy sets this header automatically.

**Comment by cleemansen** [comment] 2020-05-19 10:27
duplicate of https://github.com/rstudio/httpuv/issues/247 (?)

**Comment by jcheng5** [comment] 2020-05-19 16:42
What version of httpuv are you using? With the CRAN version of httpuv, I can't repro this (an easy way to test is with `curl -v -H "Content-Length: 0" <url>`.

**Comment by cleemansen** [comment] 2020-05-19 16:56
The best summary (incl. a bugfix / workaround) I found is https://stackoverflow.com/a/58541479/810944.

From this you can find the (accepted and merged) bugfix PR https://github.com/rstudio/httpuv/pull/248.

So I was able to solve it by using `remotes::install_github('rstudio/httpuv')` (`master`-branch of this repo). With the current `CRAN` version I did still get this issue - but perhaps this was my mistake..

For me I'm not able to identify the fix-version including this PR of `httpuv` - but I can confirm the current `master` solves this issue.

**Comment by cleemansen** [comment] 2020-05-19 16:59
BTW: it is important to request a CSS or JS-file to force this bug (`400 - Bad Request`). Requesting the index-html works fine w/ `Content-Length: 0`)

**Comment by jcheng5** [comment] 2020-05-19 18:18
Oh sorry, you're correct. https://github.com/rstudio/httpuv/blob/master/NEWS.md

We're literally in the middle of submitting httpuv to CRAN right now, FYI.

**Closed** 2020-05-19 18:18 UTC

**Comment by cleemansen** [comment] 2020-05-20 05:56
Thank you for clarification and for further information about the roadmap - that helps planning :)
