### ISSUE TITLE
user_dirs :HOME_USER: setuid/setgid prior to initializing application

### ISSUE THREAD

**Issue by serverhorror** [rstudio/shiny-server#101] opened 2015-03-18 18:01 UTC
Hi,

I'd like to use `user_dirs`, our setup is an NFS and `root_squash` so the current setup doesn't work at all

From the looks it seems like it is creating/opening user log files as root and then chowning. Please drop the privileges to that of the target user before attempting to do anything to the file system.

I hope the information below is enough for you to see my problem with the way it currently works:

Server config:
```
server {
        listen 3838;
        location /users {
          run_as :HOME_USER:;
          user_dirs;
        }
}
```

Log output:
```
[2015-03-18 18:55:48.595] [INFO] shiny-server - Shiny Server v1.3.0.0 (Node.js v0.10.21)
[2015-03-18 18:55:48.598] [INFO] shiny-server - Using config file "/etc/shiny-server/shiny-server.conf"
[2015-03-18 18:55:48.642] [INFO] shiny-server - Starting listener on 0.0.0.0:3838
[2015-03-18 18:55:52.186] [ERROR] shiny-server - Log directory creation failed: ENOENT, no such file or directory '/net/home/marcherm/ShinyApps/log'
[2015-03-18 18:55:52.786] [INFO] shiny-server - Error getting worker: Error: The application exited during initialization.
```

straced:
```
# strace -tt -e trace=mkdir,setgid,setuid shiny-server
[2015-03-18 18:59:10.376] [INFO] shiny-server - Shiny Server v1.3.0.0 (Node.js v0.10.21)
[2015-03-18 18:59:10.379] [INFO] shiny-server - Using config file "/etc/shiny-server/shiny-server.conf"
[2015-03-18 18:59:10.426] [INFO] shiny-server - Starting listener on 0.0.0.0:3838
18:59:12.867821 mkdir("/net/home/marcherm/ShinyApps/log", 0755) = -1 EACCES (Permission denied)
[2015-03-18 18:59:12.869] [ERROR] shiny-server - Log directory creation failed: ENOENT, no such file or directory '/net/home/marcherm/ShinyApps/log'
18:59:13.461572 --- SIGCHLD (Child exited) @ 0 (0) ---
[2015-03-18 18:59:13.466] [INFO] shiny-server - Error getting worker: Error: The application exited during initialization.
```

**Comment by warnes** [comment] 2015-05-26 13:49
+1

**Comment by dpryan79** [comment] 2015-07-23 13:43
:+1: from me as well. Root doesn't have permissions on our nfs exports and this is breaking deployment of user apps.

BTW, this is a duplicate of #64

**Comment by UppercutTKO** [comment] 2015-08-04 17:04
+1

**Comment by warnes** [comment] 2015-08-07 15:12
Even if the user marks everything as a+rwX, the log files will end up owned nobody.nobody so the user can't access them.

**Comment by trestletech** [comment] 2015-11-30 15:19
Closing as a duplicate of #64. Will track this issue there.

**Closed by trestletech** 2015-11-30 15:19 UTC
